# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: 5rahim.Seanime
PackageVersion: 2.8.1
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Seanime Desktop
ReleaseDate: 2025-04-13
AppsAndFeaturesEntries:
- Publisher: seanime
  ProductCode: Seanime Desktop
InstallationMetadata:
  DefaultInstallLocation: placeholder\Seanime Desktop
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/5rahim/seanime/releases/download/v2.8.1/seanime-desktop-2.8.1_Windows_x86_64.exe
  InstallerSha256: 745D37546FF31A4A83A7BBD9E3F2FE7C14D956EDADFF4342510CD21B78D182F2
ManifestType: installer
ManifestVersion: 1.9.0
